services:
  - type: web
    name: yolo-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:10000
    envVars:
      - key: YOLO_CONFIG_DIR
        value: /tmp 
